on:
    workflow_call:
        inputs:
            sonar-cloud-enabled:
                description: 'Executar ou não sonar scanner'
                required: true
                type: string
            owasp-zap-enabled:
                description: 'Executar ou não dependency check'
                required: true
                type: string
            snyk-enabled:
                description: 'Executar ou não snyk'
                required: true
                type: string
            organization:
                description: 'Organization Sonar Cloud Scan'
                required: true
                type: string

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Sonar Cloud Scan
              uses: alxss01-actions/sonar-cloud@main
              with:
                projectKey: 'br.com.devsenior:ds-devops'
                organization: ${{ inputs.organization }}
                token: ${{ secrets.SONAR_TOKEN }}
                
